services:
  bot:
    build: ./docker/bot # ビルドに使うDockerファイルのパス
    restart: always # コンテナを自動起動
    volumes:
      - ./bot:/go/src/app # マウントディレクトリ
  webhook:
    build: ./docker/webhook # ビルドに使うDockerファイルのパス
    restart: always # コンテナを自動起動
    volumes:
      - ./webhook:/go/src/app # マウントディレクトリ
  tunnel:
    restart: always # コンテナを自動起動
    image: cloudflare/cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}