services:
  bot:
    build: ./docker/bot # ビルドに使うDockerファイルのパス
    restart: always # コンテナを自動起動
    volumes:
      - .:/go/src/app # マウントディレクトリ
  webhook:
    build: ./docker/webhook # ビルドに使うDockerファイルのパス
    restart: always # コンテナを自動起動
    volumes:
      - .:/go/src/app # マウントディレクトリ
  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      - webhook
    restart: unless-stopped
    command:
      - "http"
      - "--domain=${NGROK_DOMAIN}"
      - "webhook:8080"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}